// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Network_Monitor_API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Network_Monitor_API.Migrations.SystemUsageDb
{
    [DbContext(typeof(SystemUsageDbContext))]
    partial class SystemUsageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Network_Monitor_API.Models.SystemUsageDBModels.SystemUsage", b =>
                {
                    b.Property<int>("SystemUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SystemUsageId"));

                    b.Property<int>("ActiveConnections")
                        .HasColumnType("integer");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("double precision");

                    b.Property<double>("MemoryUsage")
                        .HasColumnType("double precision");

                    b.Property<double>("NetworkUsage")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SystemUsageId");

                    b.ToTable("SystemUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
